---
title: "About"
author: "Michael Chen"
date: "2/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

The goal of this project is to conduct a data-driven analysis on the relationship between innovation rates by college (obtained from Raj Chetty's Opportunity Insights) and institution level data obtained from College Scorecard. With so much scrutiny going into whether college is really "worth it" or not, the key factor that most researchers have been examining is the earnings of students right out of college - this is the most common barometer of success. However, having read Andrew Yang's book "Smart People Should Build Things", my main concern with the "outcome" of college is whether people are creating something of value - I define value as higher innovation rates (which is measured through number of patents registered). Throughout the project, I will run regressions on various data for innovation rates (total number of patents granted to sstudents, share of inventors among students, total number of patent citations obtained by students, etc.) and various college characteristics (percentage of high income students, average SAT/ACT score, percentage of degrees awarded in various fields).

# Dataset 1

The first data source comes from Raj Chetty's Opportunity Insights data, which harnesses the power of big data to create scalable policy solutions to restore the American Dream. In the data source, the table presents estimates of students' patent rates by the college they attended, where college is what place each child attends as the institution the child attended for the greatest amount of time during the 4 calendar years in which the child turned 19-22. The most important variable is called "inventor" and represents the share of inventors among students at each college. For more information about the data source and other data on upward mobility, race and economic opportunity in the US, impact of neighborhoods, and impacts of teacher, please visit this link: https://opportunityinsights.org/data/

# Dataset 2

The other dataset I use is from the College Scorecard project - this is designed to increase transparency and provide data to help students and families compare college costs and outcomes as they weigh the tradeoffs of different colleges. The data I choose to focus on are data files with data about institutions as a whole and include variables that map each college's name, location, degree type, instituion revenue, academic areas offered, admissions rates, , SAT/ACT scores, and much more. The goal is to compare this dataset with innovation rates measured at each college and see if there are correlations between characteristics of each college and innovation rates. For more information about the College Scorecard project and its data sources, please visit this link: https://collegescorecard.ed.gov/data/

# About Me

My name is Michael Chen and I'm a current sophomore at Harvard studying Applied Math and Economics with a secondary in Government. As a co-founder of a biotech startup, I'm quite intrigued by the innovation rates at colleges and how to increase this "builder" mentality among our students. My github repo for this project can be accessed at this link: https://github.com/michaelzchen/finalproject.git. 

You can reach me at: chen_michael@college.harvard.edu or on Linkedin: https://www.linkedin.com/in/michael-c-134086135/