---
title: "Gather"
author: "Michael Chen"
date: "3/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Load libraries

library(tidyverse)
library(dplyr)
library(readr)
library(janitor)
library(gt)
library(rvest)
library(scales)
library(ggplot2)
library(ggthemes)
library(urbnmapr)
library(broom)
library(ggmap)
library(gganimate)
```

```{r downloading, include = FALSE, cache = TRUE}

# Read in the 2 datasets

colleges <- read_csv("1005 final project data/Most-Recent-Cohorts-All-Data-Elements (1).csv")
innovationRates <- read_csv("1005 final project data/innovationRates.csv")

# Clean the 2 datasets

colleges <- clean_names(colleges, "snake")
innovationRates <- clean_names(innovationRates, "snake")
```

```{r cleaning, include = FALSE}

# Select out only the variables that we are interested in the colleges dataset.
# We want to keep all the variables in the innovationRates dataset so don't
# change anything found there. Store this new data in the newColleges dataset.
# In addition, because we know we eventually want to join these 2 datasets so we
# can perform analysis, we need to ensure that the joining variable is the same
# type and same name in both datasets.

newColleges <- colleges %>%
  select(-insturl, -accredagency, -hcm2, -main, -starts_with("cip"), -starts_with("c150"), -starts_with("num"), -starts_with("dep"), -starts_with("ind"), -starts_with("female"), -starts_with("male"), -starts_with("loan"), -starts_with("noloan"), -starts_with("firstgen"), -starts_with("not1stgen"), -starts_with("pell"), -starts_with("nopell"), -starts_with("low_inc"), -starts_with("mid_inc"), -starts_with("hi_inc"), -starts_with("npt4"), -contains("rpy"), -starts_with("count"), -starts_with("mn_earn"), -starts_with("d150"), -starts_with("om"), -starts_with("ret"), -starts_with("pool"), -unitid, -opeid) %>%
  mutate(super_opeid = str_sub(opeid6, 3, -1)) %>%
  select(super_opeid, everything()) %>%
  select(-opeid6)

# Need to convert the super_opeid data frame into a numeric column so we can
# join the 2 together in both datasets.

newColleges$super_opeid <- as.numeric(as.character(newColleges$super_opeid))

# Use an inner join to merge the 2 datasets by super_opeid (the ID variable for
# each institution) and keep all the columns in both of the datasets.

joined <- inner_join(innovationRates, newColleges, by = "super_opeid")

# Remove the duplicates (if the super_opeid is the same, delete)

newJoined <- joined[!duplicated(joined$super_opeid), ]
final <- newJoined %>% select(-instnm.y)

# After creating final dataset, exported it as CSV and saved in
# Inventors-College folder via console
```

```{r ggplot, warning = FALSE}

# Now that I have the tibble I am interested in (called final), I can now create
# several plots. The first is a regression of admissions rate for each college
# against the inventors rate. Need to change adm_rate to a numeric variable to
# graph it properly. Warning = False to get rid of geom_smooth notifications
# about removing NAs in data.

final$adm_rate <- as.numeric(as.character(final$adm_rate))

# Use ggplot to graph the scatterplot, with geom_smooth to chart the
# relationship between the 2 points

ggplot(final, aes(x = adm_rate, inventor, color = inventor)) +
  geom_jitter() +
  geom_smooth(method = "loess", se = TRUE) +
  labs(title = "Regression of Admissions Rate Against Inventors", x = "Admissions Rate", y = "Percentage of Students That Are Inventors", caption = "Data Source: Opportunity Insights and College Scorecard Project") +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent)

# Save the plot

ggsave("Inventors-College/Reg_Adm_Rates_Inventors.png")
```

```{r ggplot1, warning = FALSE}

# Need to graph the relationship between first gen and inventor, to include in
# Shiny. Warning = False to get rid of geom_smooth notifications about removing
# NAs in data.

ggplot(final, aes(x = as.numeric(first_gen), inventor, color = inventor)) +
  geom_jitter() +
  geom_smooth(method = "loess", se = TRUE) +
  labs(title = "Regression of Percent of 1st Gen Students Against Inventors", x = "Share of 1st Gen", y = "Percentage of Students That Are Inventors", caption = "Data Source: Opportunity Insights and College Scorecard Project") +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent)

# Save image

ggsave("Inventors-College/Reg_1st_Gen_Inventors.png")
```

```{r ggplot2, warning = FALSE}

# Graphing the relationship between percent of full time faculty and inventor,
# to include as a static PNG in Shiny. Warning = False to get rid of geom_smooth
# notifications about removing NAs in data.

ggplot(final, aes(x = as.numeric(pftfac), inventor, color = inventor)) +
  geom_jitter() +
  geom_smooth(method = "loess", se = TRUE) +
  labs(title = "Regression of Percent of Full Time Faculty Against Inventors", x = "Percent of Full Time Faculty", y = "Percentage of Students That Are Inventors", caption = "Data Source: Opportunity Insights and College Scorecard Project") +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent)

# Save image

ggsave("Inventors-College/Reg_Perc_Faculty_Inventors.png")
```

```{r race/ethnicity, warning = FALSE}

# Plot different relationships (as segmented by races) on the same graph, to
# compare any similarities or differences

cols <- c("White" = "Blue", "Asian" = "Red", "Hispanic" = "Green", "Black" = "Black")
ggplot(final) +
  geom_smooth(data = final, aes(x = as.numeric(ugds_white), y = inventor, color = "White"), fill = "Blue") +
  geom_smooth(data = final, aes(x = as.numeric(ugds_asian), y = inventor, color = "Asian"), fill = "Red") +
  geom_smooth(data = final, aes(x = as.numeric(ugds_hisp), y = inventor, color = "Hispanic"), fill = "green") +
  geom_smooth(data = final, aes(x = as.numeric(ugds_black), y = inventor, color = "Black"), fill = "black") +
  labs(title = "Comparing Different Races Against Inventor", x = "Percent Demographic", y = "Percentage of Students That Are Inventors") +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent) +
  scale_color_manual(name = "Race", values = cols)

# Save image

ggsave("Inventors-College/Races.png")

# Plot different relationships (as segmented by gender) on the same graph, to
# compare any similarities or differences

cols1 <- c("Men" = "Blue", "Women" = "Red")
ggplot(final) +
  geom_smooth(data = final, aes(x = as.numeric(ugds_men), y = inventor, color = "Men"), fill = "Blue") +
  geom_smooth(data = final, aes(x = as.numeric(ugds_women), y = inventor, color = "Women"), fill = "Red") +
  labs(title = "Comparing Different Genders Against Inventor", x = "Percent Gender", y = "Percentage of Students That Are Inventors") +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent) +
  scale_color_manual(name = "Gender", values = cols1)

# Save image

ggsave("Inventors-College/Gender.png")

# Plot different relationships (as segmented by SAT subject) on the same graph,
# to compare any similarities or differences

cols2 <- c("Verbal" = "Blue", "Math" = "Red", "Writing" = "Black")
ggplot(final) +
  geom_smooth(data = final, aes(x = as.numeric(satvrmid), y = inventor, color = "Verbal"), fill = "Blue") +
  geom_smooth(data = final, aes(x = as.numeric(satmtmid), y = inventor, color = "Math"), fill = "Red") +
  geom_smooth(data = final, aes(x = as.numeric(satwrmid), y = inventor, color = "Writing"), fill = "Black") +
  labs(title = "Comparing Different SAT Subject Scores Against Inventor", x = "SAT Average Score", y = "Percentage of Students That Are Inventors") +
  scale_y_continuous(labels = scales::percent) +
  scale_color_manual(name = "SAT Subject", values = cols2)

# Save image

ggsave("Inventors-College/SATScores.png")

# Plot different relationships (as segmented by ACT subject) on the same graph,
# to compare any similarities or differences

cols3 <- c("Cumulative" = "Blue", "English" = "Red", "Math" = "Black")
ggplot(final) +
  geom_smooth(data = final, aes(x = as.numeric(actcmmid), y = inventor, color = "Cumulative"), fill = "Blue") +
  geom_smooth(data = final, aes(x = as.numeric(actenmid), y = inventor, color = "English"), fill = "Red") +
  geom_smooth(data = final, aes(x = as.numeric(actmtmid), y = inventor, color = "Math"), fill = "Black") +
  labs(title = "Comparing Different ACT Subject Scores Against Inventor", x = "ACT Average Score", y = "Percentage of Students That Are Inventors") +
  scale_y_continuous(labels = scales::percent) +
  scale_color_manual(name = "ACT Subject", values = cols3)

# Save image

ggsave("Inventors-College/ACTScores.png")
```
